In [0]:
## Import libraries
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding, Activation, Dropout
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GlobalMaxPooling1D 

import numpy as np
from numpy import array
import pandas as pd

In [0]:
from sklearn.model_selection import train_test_split

In [4]:
# Load the data
from google.colab import files
uploaded = files.upload()

Saving twitter4000.csv to twitter4000.csv


In [33]:
df = pd.read_csv('twitter4000.csv')
df.head()

tweets  sentiment
0  @salspizza yep those tests were in jan  so wil...          0
1  Watching A Night at the Roxbury. So hilarious....          0
2                       @allfalldown Yes. it isssss           0
3  @MonaMinx but I´ve heard they don´t  come ba...          0
4  http://twitpic.com/7oyha -  It still wont let ...          0

In [34]:
df['sentiment'].value_counts(dropna = False)

4    2000
0    2000
Name: sentiment, dtype: int64

In [35]:
text = df['tweets'].tolist()
text[:20]

['@salspizza yep those tests were in jan  so will know if i still have a heart today LOL',
 'Watching A Night at the Roxbury. So hilarious. Dude seriously fug being a girl. I have the worst cramps ever ',
 '@allfalldown Yes. it isssss ',
 '@MonaMinx but I´ve heard they don´t  come back yet this year, we all have probably wait for next year, that makes me sad ',
 'http://twitpic.com/7oyha -  It still wont let me log in.',
 '@BriColeBolt  I like you!!! Feel better!!!',
 '@Tremore why not share with the world your technological discovery? ',
 'Thanking the Lord for waking me up but not wanting to be bothered I think the phone will be on off mode today ',
 '@megandresslar when i have cried enough. ',
 'rough weekend! ',
 '@LeBron_Kingdom I know  I know. What more do the Cavs need?! Gahhh lebron with 44 pts and still lost.',
 "Hey ppls what's up the weather is more than amazing here in Toronto still wishing I was in the A with all my closest friends tho ",
 'in the CY....SORE. soresoresor

In [0]:
y = df['sentiment']

In [0]:
token = Tokenizer()
token.fit_on_texts(text)

In [38]:
token

In [50]:
## Dictionary
print(token.index_word)

{1: 'i', 2: 'the', 3: 'to', 4: 'a', 5: 'my', 6: 'and', 7: 'you', 8: 'it', 9: 'is', 10: 'in', 11: 'for', 12: 'of', 13: 'on', 14: 'so', 15: 'me', 16: 'but', 17: 'that', 18: 'have', 19: "i'm", 20: 'at', 21: 'just', 22: 'with', 23: 'be', 24: 'not', 25: 'was', 26: 'up', 27: 'good', 28: 'this', 29: 'now', 30: 'out', 31: 'get', 32: 'like', 33: 'do', 34: 'day', 35: 'all', 36: 'are', 37: 'no', 38: 'quot', 39: 'http', 40: 'go', 41: 'going', 42: "it's", 43: 'your', 44: 'today', 45: 'love', 46: 'lol', 47: 'what', 48: 'work', 49: 'from', 50: "don't", 51: 'too', 52: 'time', 53: 'com', 54: 'about', 55: 'got', 56: 'one', 57: 'back', 58: 'know', 59: 'we', 60: "can't", 61: 'u', 62: 'see', 63: 'am', 64: 'there', 65: 'amp', 66: 'will', 67: 'can', 68: 'its', 69: 'really', 70: 'want', 71: 'some', 72: 'im', 73: 'oh', 74: 'more', 75: 'night', 76: 'had', 77: 'thanks', 78: 'think', 79: 'how', 80: 'still', 81: 'home', 82: 'well', 83: 'new', 84: 'if', 85: '2', 86: 'they', 87: 'need', 88: 'off', 89: 'when', 90: 'm

In [0]:
## Total no. of unique words
vocab_size = len(token.word_index) + 1

In [56]:
vocab_size # Total no. of unique words

10027

In [0]:
# token.index_word

In [0]:
## Example of encoding
x = ['i to the a and']
# x = [1, 2, 3, 4, 6]

In [45]:
token.texts_to_sequences(x)

[[1, 3, 2, 4, 6]]

In [48]:
## We just need index (keys) of words
encoded_text = token.texts_to_sequences(text)
print(encoded_text)

[[3002, 525, 277, 1439, 155, 10, 3003, 14, 66, 58, 84, 1, 80, 18, 4, 600, 44, 46], [149, 4, 75, 20, 2, 3004, 14, 1929, 526, 494, 3005, 201, 4, 356, 1, 18, 2, 453, 3006, 247], [3007, 160, 8, 3008], [1930, 16, 3009, 468, 86, 1931, 130, 57, 307, 28, 235, 59, 35, 18, 357, 150, 11, 176, 235, 17, 308, 15, 101], [39, 156, 53, 3010, 8, 80, 887, 220, 15, 1440, 10], [3011, 1, 32, 7, 105, 123], [3012, 109, 24, 714, 22, 2, 309, 43, 3013, 3014], [3015, 2, 1185, 11, 715, 15, 26, 16, 24, 1441, 3, 23, 3016, 1, 78, 2, 263, 66, 23, 13, 88, 1932, 44], [3017, 89, 1, 18, 1019, 495], [1442, 131], [1020, 1933, 1, 58, 1, 58, 47, 74, 33, 2, 1934, 87, 3018, 1020, 22, 3019, 3020, 6, 80, 225], [177, 3021, 527, 26, 2, 286, 9, 74, 178, 287, 97, 10, 1443, 80, 888, 1, 25, 10, 2, 4, 22, 35, 5, 1935, 226, 341], [10, 2, 3022, 791, 3023, 1444, 212, 561, 20, 2, 236, 12, 2, 562], [5, 563, 237, 36, 35, 1936, 12, 1186, 26, 93, 563, 454, 25, 227, 288, 601, 358, 9, 716, 26, 99, 602, 3024, 1937], [3025, 89, 7, 297, 326, 359, 13

In [0]:
## Note from above out put
## -- Each vector above might have different size
## -- So therefore we need pad_sequence

max_length = 120 ## All tweets can have maximum words of 120 ---LOL
X = pad_sequences(encoded_text, maxlen = max_length, padding = 'post')

In [52]:
print(X)

[[ 3002   525   277 ...     0     0     0]
 [  149     4    75 ...     0     0     0]
 [ 3007   160     8 ...     0     0     0]
 ...
 [10023     1    21 ...     0     0     0]
 [10024    46     1 ...     0     0     0]
 [   37    15 10025 ...     0     0     0]]


In [53]:
X.shape

(4000, 120)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    random_state = 42, 
                                                    test_size = 0.2,
                                                    stratify = y)

In [0]:
vec_size = 300

model = Sequential()
model.add(Embedding(vocab_size, vec_size, input_length = max_length))

## convolution layer
model.add(Conv1D(64, 8, activation = 'relu'))
model.add(MaxPooling1D(2)) # with 2 data
model.add(Dropout(0.5))

model.add(Dense(32, activation = 'relu'))
model.add(Dropout(0.5))

model.add(Dense(16, activation = 'relu'))

model.add(GlobalMaxPooling1D())


model.add(Dense(1, activation = 'sigmoid'))



In [0]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [59]:
%%time
model.fit(X_train, y_train, epochs = 5, valdiation_data = (X_test, y_test))

Epoch 1/5
100/100 [==============================] - 12s 124ms/step - loss: -950.3553 - accuracy: 0.0000e+00
Epoch 2/5
100/100 [==============================] - 12s 124ms/step - loss: -76955.6172 - accuracy: 0.0000e+00
Epoch 3/5
100/100 [==============================] - 12s 123ms/step - loss: -1184223.0000 - accuracy: 0.0000e+00
Epoch 4/5
100/100 [==============================] - 12s 124ms/step - loss: -7496986.0000 - accuracy: 0.0000e+00
Epoch 5/5
100/100 [==============================] - 12s 124ms/step - loss: -29352328.0000 - accuracy: 0.0000e+00
CPU times: user 1min 54s, sys: 2.89 s, total: 1min 57s
Wall time: 1min 3s


In [0]:
def get_encoded(x):
    x = token.texts_to_sequences(x)
    x = pad_sequences(x, maxlen = max_length, padding='post')
    return x

In [0]:
x = [' worst services. will not not come again']

In [62]:
model.predict_classes(get_encoded(x))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[1]], dtype=int32)

In [0]:
x = [' thank you for watching']

In [64]:
model.predict_classes(get_encoded(x))

array([[1]], dtype=int32)